# -*- mode: org; -*-

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/bigblow/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/bigblow/css/bigblow.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="http://www.pirilampo.org/styles/bigblow/css/hideshow.css"/>

#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/jquery-1.11.0.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/jquery-ui-1.10.2.min.js"></script>

#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/jquery.localscroll-min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/jquery.scrollTo-1.4.3.1-min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/jquery.zclip.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/bigblow.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="http://www.pirilampo.org/styles/bigblow/js/hideshow.js"></script>

* Overview

My configuration files to work in an efficient way, or I think so :)

** Terminal

The place I spent half the time. I like using [[http://rxvt.sourceforge.net/][rxvt]] as my main terminal emulator on linux.

Under the rxvt directory you can find several Xresources files, which is the preferred way to configure rxvt instead of Xdefaults.

#+BEGIN_SRC sh
sudo yum install rxvt-unicode
cp rxvt/Xresources ~/.Xresources
#+END_SRC

Personally I prefer to launch rxvt in daemon mode (*urxvtd*) and create clients (*urxvtc*) as I need them.

** emacs

My customizations to show line numbers, and use several modes for grails, groovy and XML development.

Recently I moved to [[http://overtone.github.io/emacs-live/][emacs live]], you can see my customizations [[https://github.com/jm2dev/emacs-live-jm-pack][here]].
** xrandr

Script to configure my dual display desktop.

** tmux

My nice tmux configuration, I forgot where I found it so credits are
owned. Copy the tmux.conf file to $HOME/.tmux.conf

** fedora

I need to customize my freebsd/debian version settings to work in
Fedora.

** i3

A tiling window manager, like xmonad. You need to copy *config* to
~/.i3/config.
** redshift

[[http://jonls.dk/redshift/][Redshift]] is an application to adjust the colour temperature of the screen. See my settings for London in that folder, and copy the file to ~/.config/redshift.conf.
